### ISSUE TITLE
Link vom Drucksensor für zu einer Led Taschenlampe

### ISSUE THREAD

**Issue by Triton-KS** [jp112sdl/HB-UNI-Sen-PRESS#2]
Hallo,
irgendwie führt der Link vom Drucksensor zu einer Led Taschenlampe.
Was sollte man bei eine alternativen Suche beachten oder gibt es einen alternativen Link?

Dankeschön

**Comment by jp112sdl** [comment]
Danke für den Hinweis.
Da wurde die Artikelnummer irgendwann wieder neu vergeben -.-
Hab den Link dann lieber ganz entfernt.

Sowas hier geht:
https://www.ebay.de/itm/G1-4-5V-0-1-2-MPa-Druckaufnehmer-Sensor-Ol-Kraftstoff-Diesel-Gas-Wasser-Luft/313340203234
